language: java
jdk:
  - oraclejdk8
script:
  - mvn verify
after_success:
  - mvn clean test jacoco:report coveralls:report
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml